/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTAS;

import guia.telefonica.Herramientas;

/**
 *
 * @author Max
 */
public class Busqueda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        BotonCiudad = new javax.swing.JToggleButton();
        BotonTelefono = new javax.swing.JToggleButton();
        BotonApellido = new javax.swing.JToggleButton();
        CampoDeIngreso = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        BotonAceptar = new javax.swing.JButton();

        setTitle("Busqueda");

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2.setBackground(java.awt.Color.white);
        Panel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Panel2.setForeground(java.awt.Color.white);
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelTitulo.setForeground(java.awt.Color.black);
        LabelTitulo.setText("Seleccione el Criterio de Busqueda");
        Panel2.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 43));

        BotonCiudad.setText("Por Ciudad");
        Panel2.add(BotonCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, 40));

        BotonTelefono.setText("Por Telefono");
        BotonTelefono.setToolTipText("");
        BotonTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonTelefono.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BotonTelefonoItemStateChanged(evt);
            }
        });
        Panel2.add(BotonTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 40));

        BotonApellido.setText("Por Apellido");
        Panel2.add(BotonApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 40));
        Panel2.add(CampoDeIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 300, 40));

        Buscar.setText("Buscar");
        Panel2.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 110, 50));

        jPanel1.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un contacto" }));
        ComboBox.setToolTipText("");
        jPanel1.add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 410, 30));

        BotonAceptar.setText("Aceptar");
        jPanel1.add(BotonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 524, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTelefonoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BotonTelefonoItemStateChanged
        Herramientas.comprobarSiElBotonEstaSeleccionado(BotonTelefono, "Telefono", 1);
    }//GEN-LAST:event_BotonTelefonoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JToggleButton BotonApellido;
    private javax.swing.JToggleButton BotonCiudad;
    private javax.swing.JToggleButton BotonTelefono;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField CampoDeIngreso;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
